CREATE DATABASE yeticave
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;



USE yeticave;



CREATE TABLE categories(
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(128) NOT NULL,
	char_code VARCHAR(64) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;



CREATE TABLE lots(
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(128) NOT NULL,
	description TEXT NOT NULL,
	picture_path VARCHAR(128) NOT NULL,
	start_price INT(11) NOT NULL,
	dt_end TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	bid_step INT(11) NOT NULL,
	cat_id INT(11),
	user_id INT(11)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;



CREATE TABLE bids(
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	offer_price INT(11) NOT NULL,
	lot_id INT(11),
	user_id INT(11)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;



CREATE TABLE users(
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	dt_reg TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(128) NOT NULL UNIQUE,
	name VARCHAR(128) NOT NULL,
	hashed_password VARCHAR(128) NOT NULL,
	contacts_info VARCHAR(128)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
